# Generated by Django 4.2.7 on 2026-06-12 07:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('mission_created', 'Mission créée'), ('mission_accepted', 'Mission acceptée'), ('mission_started', 'Mission démarrée'), ('mission_submitted', 'Preuves soumises'), ('mission_completed', 'Mission terminée'), ('mission_cancelled', 'Mission annulée'), ('mission_expired', 'Mission expirée'), ('payment_received', 'Paiement reçu'), ('payment_sent', 'Paiement envoyé'), ('deposit_locked', 'Caution bloquée'), ('deposit_released', 'Caution libérée'), ('refund_processed', 'Remboursement effectué'), ('dispute_opened', 'Litige ouvert'), ('dispute_updated', 'Litige mis à jour'), ('dispute_resolved', 'Litige résolu'), ('reputation_updated', 'Réputation mise à jour'), ('level_up', 'Niveau supérieur'), ('kyc_verified', 'KYC vérifié'), ('kyc_rejected', 'KYC rejeté'), ('message_received', 'Message reçu'), ('system_announcement', 'Annonce système'), ('promotion', 'Promotion'), ('gps_location', 'Mise à jour GPS'), ('mission_reminder', 'Rappel mission')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], default='normal', max_length=10)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('push', 'Push'), ('email', 'Email'), ('sms', 'SMS'), ('all', 'Tous')], default='all', max_length=10)),
                ('image_url', models.URLField(blank=True)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('in_app_sent', models.BooleanField(default=False)),
                ('push_sent', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('push_token', models.CharField(blank=True, max_length=255)),
                ('email_recipient', models.EmailField(blank=True, max_length=254)),
                ('sms_recipient', models.CharField(blank=True, max_length=17)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_mission_updates', models.BooleanField(default=True)),
                ('email_payments', models.BooleanField(default=True)),
                ('email_disputes', models.BooleanField(default=True)),
                ('email_marketing', models.BooleanField(default=False)),
                ('email_digest', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('push_mission_updates', models.BooleanField(default=True)),
                ('push_payments', models.BooleanField(default=True)),
                ('push_messages', models.BooleanField(default=True)),
                ('push_gps', models.BooleanField(default=False)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('sms_urgent_only', models.BooleanField(default=True)),
                ('sms_security', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('in_app_sound', models.BooleanField(default=True)),
                ('in_app_vibration', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Africa/Abidjan', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], max_length=10)),
                ('notification_type', models.CharField(max_length=30)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('title_template', models.CharField(max_length=255)),
                ('message_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.CharField(default='fr', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.CharField(max_length=255, unique=True)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(max_length=20)),
                ('device_model', models.CharField(blank=True, max_length=100)),
                ('os_version', models.CharField(blank=True, max_length=50)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'push_subscriptions',
                'ordering': ['-last_used_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Planifiée'), ('sent', 'Envoyée'), ('cancelled', 'Annulée'), ('failed', 'Échouée')], default='scheduled', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scheduled_notifications',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
