# Generated by Django 4.2.30 on 2026-06-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='timezone',
            field=models.CharField(default='Africa/Bamako', max_length=50),
        ),
    ]
