# Generated by Django 4.2.7 on 2026-07-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_pan_africa_market_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_compact',
            field=models.BooleanField(default=False, help_text='Notification compacte avec texte limité'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_minimal',
            field=models.BooleanField(default=False, help_text='Notification minimale avec icône seulement'),
        ),
    ]
