# Generated by Django 4.2.7 on 2026-07-18 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_add_compact_notification_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_compact',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_minimal',
        ),
    ]
