# Generated by Django 4.2.7 on 2026-06-12 07:28

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mission_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('pickup_address', models.TextField(blank=True)),
                ('pickup_latitude', models.FloatField(blank=True, null=True)),
                ('pickup_longitude', models.FloatField(blank=True, null=True)),
                ('delivery_address', models.TextField(blank=True)),
                ('delivery_latitude', models.FloatField(blank=True, null=True)),
                ('delivery_longitude', models.FloatField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('required_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('deposit_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('deadline', models.DateTimeField()),
                ('expected_duration', models.PositiveIntegerField(default=60, help_text='Durée estimée en minutes')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('funded', 'Financée'), ('accepted', 'Acceptée'), ('in_progress', 'En cours'), ('submitted', 'Preuves soumises'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('disputed', 'En litige'), ('expired', 'Expirée')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], default='normal', max_length=20)),
                ('requires_verified_provider', models.BooleanField(default=False)),
                ('min_reputation_score', models.FloatField(default=0)),
                ('enterprise_only', models.BooleanField(default=False)),
                ('requires_gps_tracking', models.BooleanField(default=True)),
                ('requires_qr_validation', models.BooleanField(default=False)),
                ('auto_validation_delay', models.PositiveIntegerField(default=24, help_text='Heures avant validation auto')),
                ('auto_validation_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('escrow_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('mission_contract_id', models.PositiveIntegerField(blank=True, null=True)),
                ('blockchain_status', models.CharField(default='pending', max_length=20)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('applications_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'missions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('message', models.TextField(blank=True)),
                ('estimated_duration', models.PositiveIntegerField(blank=True, help_text='Minutes', null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée'), ('withdrawn', 'Retirée')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mission_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mission_bookmarks',
            },
        ),
        migrations.CreateModel(
            name='MissionCategoryPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mission_category_prices',
            },
        ),
        migrations.CreateModel(
            name='MissionReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('client_comment', models.TextField(blank=True)),
                ('client_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('provider_comment', models.TextField(blank=True)),
                ('provider_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('client_reported_issue', models.TextField(blank=True)),
                ('provider_reported_issue', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mission_reviews',
            },
        ),
        migrations.CreateModel(
            name='MissionStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Mission Status Histories',
                'db_table': 'mission_status_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
