# Generated by Django 4.2.7 on 2026-06-12 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='missionstatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='missionstatushistory',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='missionreview',
            name='mission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='missioncategoryprice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.category'),
        ),
        migrations.AddField(
            model_name='missionbookmark',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='missionbookmark',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_missions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='missionapplication',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='missionapplication',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mission',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='missions.category'),
        ),
        migrations.AddField(
            model_name='mission',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_missions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mission',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_missions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='missioncategoryprice',
            unique_together={('category', 'city')},
        ),
        migrations.AlterUniqueTogether(
            name='missionbookmark',
            unique_together={('provider', 'mission')},
        ),
        migrations.AlterUniqueTogether(
            name='missionapplication',
            unique_together={('mission', 'provider')},
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['status', 'created_at'], name='missions_status_dc0ef5_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['client', 'status'], name='missions_client__5e9294_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['provider', 'status'], name='missions_provide_6e0155_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['category', 'status'], name='missions_categor_2ebdd2_idx'),
        ),
    ]
