# Generated by Django 4.2.30 on 2026-06-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='deposit_deadline',
            field=models.DateTimeField(blank=True, help_text='Délai pour déposer la caution après acceptation (4h par défaut)', null=True),
        ),
    ]
