# Generated by Django 4.2.30 on 2026-06-23 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_backfill_dual_roles'),
        ('missions', '0004_mission_solicitations'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='missionsolicitation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='missionsolicitation',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_solicitations', to='users.enterpriseprofile'),
        ),
        migrations.AddField(
            model_name='missionsolicitation',
            name='target_type',
            field=models.CharField(choices=[('provider', 'Prestataire'), ('enterprise', 'Entreprise')], default='provider', max_length=20),
        ),
        migrations.AlterField(
            model_name='missionsolicitation',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_solicitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
