# Generated by Django 4.2.7 on 2026-07-25 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0003_team_members_multi_exec'),
        ('users', '0012_enterprise_recruitment_calls'),
        ('missions', '0011_mission_listing_mode'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='missionmedia',
            new_name='mission_med_mission_5779ec_idx',
            old_name='mission_med_mission_6c0a0a_idx',
        ),
        migrations.AddField(
            model_name='mission',
            name='assigned_team',
            field=models.ForeignKey(blank=True, help_text='Équipe entreprise affectée (si affectation par équipe)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='enterprises.enterpriseteam'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='executing_employee',
            field=models.ForeignKey(blank=True, help_text="Chef d'équipe / employé principal qui exécute la mission", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_missions', to='users.employee'),
        ),
    ]
