# Generated by Django 4.2.7 on 2026-07-25 18:54

from django.db import migrations, models


def backfill_status_before_dispute(apps, schema_editor):
    Mission = apps.get_model('missions', 'Mission')
    MissionStatusHistory = apps.get_model('missions', 'MissionStatusHistory')
    for mission in Mission.objects.filter(status='disputed', status_before_dispute__isnull=True):
        hist = (
            MissionStatusHistory.objects
            .filter(mission_id=mission.id, new_status='disputed')
            .order_by('-created_at')
            .first()
        )
        if hist and hist.old_status and hist.old_status != 'disputed':
            mission.status_before_dispute = hist.old_status
            mission.save(update_fields=['status_before_dispute'])


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0012_team_members_multi_exec'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='status_before_dispute',
            field=models.CharField(blank=True, help_text='Statut métier juste avant le passage en litige', max_length=20, null=True),
        ),
        migrations.RunPython(backfill_status_before_dispute, migrations.RunPython.noop),
    ]
