# Generated by Django 4.2.7 on 2026-06-12 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
        ('escrow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerdeposit',
            name='locked_for_mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_deposits', to='missions.mission'),
        ),
    ]
