# Generated by Django 4.2.7 on 2026-06-12 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escrow', '0002_initial'),
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='providerdeposit',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_logs', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_escrow_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_transactions', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_escrow_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blockchainevent',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_events', to='missions.mission'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['mission', 'status'], name='escrow_escr_mission_6db7dc_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['client', 'status'], name='escrow_escr_client__c4ec2d_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['provider', 'status'], name='escrow_escr_provide_b5efab_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['deposit_tx_hash'], name='escrow_escr_deposit_67a955_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['created_at'], name='escrow_escr_created_aba3a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blockchainevent',
            unique_together={('transaction_hash', 'log_index')},
        ),
    ]
