# Generated by Django 4.2.7 on 2026-06-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_role',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('provider', 'Prestataire'), ('enterprise', 'Entreprise'), ('admin', 'Administrateur')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='secondary_role',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('provider', 'Prestataire'), ('enterprise', 'Entreprise'), ('admin', 'Administrateur')], max_length=20, null=True),
        ),
    ]
