# Generated by Django 4.2.7 on 2026-06-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_secondary_role_active_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gps_tracking_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
