# Generated by Django 4.2.30 on 2026-06-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_gps_tracking_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='Mali', max_length=100),
        ),
    ]
