# Generated by Django 4.2.7 on 2026-07-18 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_20250630'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kyc_admin_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_admin_override_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_admin_override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_admin_override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_ai_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_ai_analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_ai_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_ai_decision',
            field=models.CharField(blank=True, choices=[('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('manual_review', 'Revue manuelle')], max_length=20, null=True),
        ),
    ]
