# Generated by Django 4.2.7 on 2026-07-25 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_employee_multi_enterprise_invites'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseRecruitmentApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Refusée'), ('withdrawn', 'Retirée')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'enterprise_recruitment_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseRecruitmentCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('manager', 'Manager'), ('accountant', 'Comptable'), ('hr', 'Ressources Humaines'), ('agent', 'Agent')], default='agent', max_length=20)),
                ('position', models.CharField(blank=True, default='Agent terrain', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('requirements', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('closed', 'Fermé'), ('cancelled', 'Annulé')], db_index=True, default='open', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'enterprise_recruitment_calls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='enterpriseinvite',
            new_name='enterprise__email_2964d0_idx',
            old_name='enterprise__email_7c8a1a_idx',
        ),
        migrations.RenameIndex(
            model_name='enterpriseinvite',
            new_name='enterprise__enterpr_6dc3e4_idx',
            old_name='enterprise__enterpr_9b2c4d_idx',
        ),
        migrations.AddField(
            model_name='enterpriserecruitmentcall',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recruitment_calls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enterpriserecruitmentcall',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_calls', to='users.enterpriseprofile'),
        ),
        migrations.AddField(
            model_name='enterpriserecruitmentapplication',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.enterpriserecruitmentcall'),
        ),
        migrations.AddField(
            model_name='enterpriserecruitmentapplication',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='enterpriserecruitmentcall',
            index=models.Index(fields=['status', 'created_at'], name='enterprise__status_c7777b_idx'),
        ),
        migrations.AddIndex(
            model_name='enterpriserecruitmentcall',
            index=models.Index(fields=['enterprise', 'status'], name='enterprise__enterpr_814a41_idx'),
        ),
        migrations.AddConstraint(
            model_name='enterpriserecruitmentapplication',
            constraint=models.UniqueConstraint(fields=('call', 'provider'), name='uniq_recruitment_application_call_provider'),
        ),
    ]
