# Generated by Django 4.2.7 on 2026-07-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_enterprise_recruitment_calls'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pay_phone',
            field=models.CharField(blank=True, help_text='Numéro Mobile Money pour la rémunération employé', max_length=17),
        ),
        migrations.AddField(
            model_name='employee',
            name='pay_weight',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Poids relatif pour le partage des gains (1.0 = normal)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Dépôt'), ('withdrawal', 'Retrait'), ('mission_payment', 'Paiement Mission'), ('refund', 'Remboursement'), ('commission', 'Commission'), ('deposit_lock', 'Blocage Caution'), ('deposit_release', 'Libération Caution'), ('employee_payroll', 'Paie employé')], max_length=30),
        ),
    ]
