# Generated by Django 4.2.7 on 2026-06-12 07:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_resolve_disputes', models.BooleanField(default=True)),
                ('can_moderate_content', models.BooleanField(default=False)),
                ('can_suspend_users', models.BooleanField(default=False)),
                ('disputes_handled', models.PositiveIntegerField(default=0)),
                ('disputes_resolved', models.PositiveIntegerField(default=0)),
                ('avg_resolution_time', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'arbitrators',
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispute_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('reason', models.CharField(choices=[('non_delivery', 'Non livraison'), ('late_delivery', 'Livraison en retard'), ('damaged_item', 'Article endommagé'), ('wrong_item', 'Mauvais article'), ('poor_quality', 'Mauvaise qualité'), ('incomplete_work', 'Travail incomplet'), ('fake_proof', 'Fausse preuve'), ('payment_issue', 'Problème de paiement'), ('behavior', 'Comportement inapproprié'), ('other', 'Autre')], max_length=30)),
                ('description', models.TextField()),
                ('requested_resolution', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('under_review', "En cours d'examen"), ('pending_evidence', 'Preuves en attente'), ('arbitration', 'Arbitrage'), ('resolved', 'Résolu'), ('appealed', 'En appel'), ('closed', 'Fermé')], default='open', max_length=20)),
                ('decision', models.CharField(choices=[('pending', 'En attente'), ('client_wins', 'Client gagne'), ('provider_wins', 'Prestataire gagne'), ('split', 'Partage 50/50'), ('partial_client', 'Remboursement partiel client'), ('partial_provider', 'Paiement partiel prestataire')], default='pending', max_length=20)),
                ('decision_reason', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('client_refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('provider_payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('deposit_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dispute_contract_id', models.PositiveIntegerField(blank=True, null=True)),
                ('decision_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('evidence_deadline', models.DateTimeField(blank=True, null=True)),
                ('auto_resolve_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'disputes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeAppeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('new_evidence', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('under_review', "En cours d'examen"), ('accepted', 'Accepté'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dispute_appeals',
            },
        ),
        migrations.CreateModel(
            name='DisputeCategoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, unique=True)),
                ('resolution_deadline_hours', models.PositiveIntegerField(default=72)),
                ('max_refund_percent', models.PositiveSmallIntegerField(default=100)),
                ('min_penalty_percent', models.PositiveSmallIntegerField(default=0)),
                ('requires_expert', models.BooleanField(default=False)),
                ('requires_site_visit', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'dispute_category_rules',
            },
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo'), ('document', 'Document'), ('audio', 'Audio'), ('screenshot', "Capture d'écran"), ('chat_log', 'Historique de conversation'), ('gps_data', 'Données GPS'), ('signature', 'Signature'), ('receipt', 'Reçu'), ('witness', 'Témoignage'), ('expert', "Rapport d'expert")], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='disputes/evidence/')),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('blockchain_proof_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_accepted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Dispute Evidence',
                'db_table': 'dispute_evidence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='disputes.dispute')),
            ],
            options={
                'db_table': 'dispute_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
