# Generated by Django 4.2.7 on 2026-06-12 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disputes', '0001_initial'),
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='disputemessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputeevidence',
            name='dispute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='disputes.dispute'),
        ),
        migrations.AddField(
            model_name='disputeevidence',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputeappeal',
            name='appellant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals_filed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputeappeal',
            name='original_dispute',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='disputes.dispute'),
        ),
        migrations.AddField(
            model_name='disputeappeal',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='disputes.arbitrator'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='defendant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='plaintiff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_filed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arbitrator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrator_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
