# Generated by Django 4.2.7 on 2026-07-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='defendant_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='defendant_response',
            field=models.TextField(blank=True),
        ),
    ]
