# Generated by Django 4.2.7 on 2026-06-12 07:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_type', models.CharField(choices=[('pickup', 'Point de retrait'), ('delivery', 'Point de livraison'), ('checkpoint', 'Point de contrôle'), ('current', 'Position actuelle'), ('start', 'Début mission'), ('end', 'Fin mission')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('battery_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gps_locations',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MissionProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proof_type', models.CharField(choices=[('photo_before', 'Photo - Avant'), ('photo_during', 'Photo - Pendant'), ('photo_after', 'Photo - Après'), ('video', 'Vidéo'), ('signature_client', 'Signature Client'), ('signature_provider', 'Signature Prestataire'), ('gps_location', 'Localisation GPS'), ('qr_code', 'QR Code'), ('receipt', 'Reçu'), ('document', 'Document'), ('barcode', 'Code-barres'), ('timestamp', 'Horodatage'), ('checklist', 'Checklist')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='missions/proofs/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('ipfs_hash', models.CharField(blank=True, max_length=64)),
                ('blockchain_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'En attente'), ('verified', 'Vérifié'), ('rejected', 'Rejeté'), ('flagged', 'Signalé')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mission_proofs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objects_detected', models.JSONField(blank=True, default=list)),
                ('text_detected', models.TextField(blank=True)),
                ('faces_count', models.PositiveSmallIntegerField(default=0)),
                ('is_blurry', models.BooleanField(default=False)),
                ('blur_score', models.FloatField(blank=True, null=True)),
                ('is_dark', models.BooleanField(default=False)),
                ('brightness_score', models.FloatField(blank=True, null=True)),
                ('exif_timestamp', models.DateTimeField(blank=True, null=True)),
                ('matches_mission_location', models.BooleanField(default=False)),
                ('distance_from_mission', models.FloatField(blank=True, null=True)),
                ('fraud_score', models.FloatField(default=0)),
                ('fraud_flags', models.JSONField(blank=True, default=list)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'photo_analyses',
            },
        ),
        migrations.CreateModel(
            name='ProofChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requires_pickup_photo', models.BooleanField(default=False)),
                ('requires_delivery_photo', models.BooleanField(default=False)),
                ('requires_signature', models.BooleanField(default=False)),
                ('requires_qr_code', models.BooleanField(default=False)),
                ('requires_receipt', models.BooleanField(default=False)),
                ('pickup_photo_done', models.BooleanField(default=False)),
                ('delivery_photo_done', models.BooleanField(default=False)),
                ('signature_done', models.BooleanField(default=False)),
                ('qr_code_done', models.BooleanField(default=False)),
                ('receipt_done', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'proof_checklists',
            },
        ),
        migrations.CreateModel(
            name='QRValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_code_data', models.TextField()),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('scanned', 'Scanné'), ('validated', 'Validé'), ('expired', 'Expiré'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qr_validations',
            },
        ),
        migrations.CreateModel(
            name='SignatureRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signer_role', models.CharField(max_length=20)),
                ('signature_image', models.ImageField(upload_to='signatures/')),
                ('signature_data', models.JSONField()),
                ('signed_at', models.DateTimeField()),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_notes', models.TextField(blank=True)),
                ('blockchain_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='missions.mission')),
            ],
            options={
                'db_table': 'signature_records',
                'ordering': ['-signed_at'],
            },
        ),
    ]
