# Generated by Django 4.2.7 on 2026-06-12 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('missions', '0002_initial'),
        ('proofs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturerecord',
            name='signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qrvalidation',
            name='mission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_validation', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='qrvalidation',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proofchecklist',
            name='mission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proof_checklist', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='photoanalysis',
            name='proof',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='proofs.missionproof'),
        ),
        migrations.AddField(
            model_name='missionproof',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='missionproof',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_proofs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='missionproof',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_proofs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gpslocation',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_locations', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='gpslocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='gpslocation',
            index=models.Index(fields=['mission', 'timestamp'], name='gps_locatio_mission_cb4ea5_idx'),
        ),
        migrations.AddIndex(
            model_name='gpslocation',
            index=models.Index(fields=['user', 'timestamp'], name='gps_locatio_user_id_ce9a55_idx'),
        ),
    ]
