# Generated by Django 4.2.7 on 2026-06-12 07:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_type', models.CharField(choices=[('manual', 'Manuelle'), ('automatic', 'Automatique'), ('rotation', 'Rotation')], default='manual', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('busy', 'Occupé'), ('on_mission', 'En mission'), ('on_break', 'En pause'), ('offline', 'Hors ligne'), ('vacation', 'En congé')], default='offline', max_length=20)),
                ('current_latitude', models.FloatField(blank=True, null=True)),
                ('current_longitude', models.FloatField(blank=True, null=True)),
                ('location_updated_at', models.DateTimeField(blank=True, null=True)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employee_availability',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_working', models.BooleanField(default=True)),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee_schedules',
            },
        ),
        migrations.CreateModel(
            name='EnterpriseAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('missions_created', models.PositiveIntegerField(default=0)),
                ('missions_completed', models.PositiveIntegerField(default=0)),
                ('missions_cancelled', models.PositiveIntegerField(default=0)),
                ('missions_disputed', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_paid_to_providers', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('avg_completion_time', models.FloatField(default=0)),
                ('on_time_rate', models.FloatField(default=100)),
                ('customer_satisfaction', models.FloatField(default=5)),
                ('active_employees', models.PositiveIntegerField(default=0)),
                ('employee_utilization', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'enterprise_analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_type', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Entreprise')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu'), ('expired', 'Expiré'), ('terminated', 'Résilié')], default='active', max_length=20)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('max_employees', models.PositiveIntegerField(default=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('billing_email', models.EmailField(max_length=254)),
                ('billing_address', models.TextField()),
                ('contract_document', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'enterprise_contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('paid', 'Payée'), ('overdue', 'En retard'), ('cancelled', 'Annulée')], default='draft', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
            ],
            options={
                'db_table': 'enterprise_invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'enterprise_teams',
            },
        ),
    ]
