# Generated by Django 4.2.7 on 2026-06-12 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enterprises', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseteam',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='users.enterpriseprofile'),
        ),
        migrations.AddField(
            model_name='enterpriseteam',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_teams', to='users.employee'),
        ),
        migrations.AddField(
            model_name='enterpriseinvoice',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprises.enterprisecontract'),
        ),
        migrations.AddField(
            model_name='enterpriseinvoice',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='users.enterpriseprofile'),
        ),
        migrations.AddField(
            model_name='enterprisecontract',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='users.enterpriseprofile'),
        ),
        migrations.AddField(
            model_name='enterpriseanalytics',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='users.enterpriseprofile'),
        ),
        migrations.AddField(
            model_name='employeeschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='users.employee'),
        ),
        migrations.AddField(
            model_name='employeeavailability',
            name='current_mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_employees', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='employeeavailability',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='users.employee'),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='users.employee'),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='missions.mission'),
        ),
        migrations.AlterUniqueTogether(
            name='enterpriseanalytics',
            unique_together={('enterprise', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='employeeschedule',
            unique_together={('employee', 'day_of_week')},
        ),
    ]
