# Generated by Django 4.2.7 on 2026-07-25 09:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_enterprise_recruitment_calls'),
        ('enterprises', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseTeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_lead', models.BooleanField(default=False, help_text='Marqueur local (le chef officiel reste team.manager)')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'enterprise_team_members',
            },
        ),
        migrations.AlterModelOptions(
            name='enterpriseteam',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='is_lead',
            field=models.BooleanField(default=False, help_text="Chef d'équipe pour cette mission"),
        ),
        migrations.AddField(
            model_name='enterpriseteam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='employeeassignment',
            constraint=models.UniqueConstraint(fields=('mission', 'employee'), name='uniq_assignment_mission_employee'),
        ),
        migrations.AddField(
            model_name='enterpriseteammember',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='users.employee'),
        ),
        migrations.AddField(
            model_name='enterpriseteammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='enterprises.enterpriseteam'),
        ),
        migrations.AddConstraint(
            model_name='enterpriseteammember',
            constraint=models.UniqueConstraint(fields=('team', 'employee'), name='uniq_team_member'),
        ),
    ]
