# Generated by Django 4.2.7 on 2026-07-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0003_team_members_multi_exec'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseteammember',
            name='category',
            field=models.CharField(blank=True, default='', help_text="Catégorie / spécialité du membre dans l'équipe (optionnel)", max_length=100),
        ),
    ]
