# Generated by Django 4.2.7 on 2026-07-26 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_employee_payroll'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('missions', '0013_status_before_dispute_and_defense'),
        ('enterprises', '0004_team_member_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('weekly', 'Hebdomadaire'), ('monthly', 'Mensuelle')], max_length=20)),
                ('payment_mode', models.CharField(choices=[('automatic', 'Automatique'), ('manual', 'Manuel')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending_approval', 'En attente validation'), ('approved', 'Approuvée'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='draft', max_length=20)),
                ('employees_count', models.PositiveIntegerField(default=0)),
                ('missions_count', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_periods_approved', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_periods', to='users.enterpriseprofile')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_periods_generated', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_periods_paid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_periods',
                'ordering': ['-period_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('missions_count', models.PositiveIntegerField(default=0)),
                ('solo_missions', models.PositiveIntegerField(default=0)),
                ('team_missions', models.PositiveIntegerField(default=0)),
                ('lead_missions', models.PositiveIntegerField(default=0)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payée'), ('skipped', 'Ignorée')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_lines', to='users.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='enterprises.payrollperiod')),
            ],
            options={
                'db_table': 'payroll_lines',
                'ordering': ['-net_amount'],
            },
        ),
        migrations.CreateModel(
            name='MissionEmployeeEarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mission_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mission_net', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pool_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_team', models.BooleanField(default=False)),
                ('is_lead', models.BooleanField(default=False)),
                ('team_size', models.PositiveIntegerField(default=1)),
                ('share_weight', models.DecimalField(decimal_places=4, default=1, max_digits=8)),
                ('share_ratio', models.DecimalField(decimal_places=6, default=1, max_digits=8)),
                ('status', models.CharField(choices=[('accrued', 'Accru'), ('included', 'Inclus dans une période'), ('paid', 'Payé'), ('cancelled', 'Annulé')], default='accrued', max_length=20)),
                ('accrued_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='users.employee')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_earnings', to='users.enterpriseprofile')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_earnings', to='missions.mission')),
                ('payroll_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to='enterprises.payrollline')),
            ],
            options={
                'db_table': 'mission_employee_earnings',
                'ordering': ['-accrued_at'],
            },
        ),
        migrations.CreateModel(
            name='EnterprisePayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('weekly', 'Hebdomadaire'), ('monthly', 'Mensuelle')], default='weekly', max_length=20)),
                ('payment_mode', models.CharField(choices=[('automatic', 'Automatique'), ('manual', 'Manuel')], default='manual', max_length=20)),
                ('employee_pool_percent', models.DecimalField(decimal_places=2, default=70, help_text="% du montant net mission versé au pool employés (le reste reste à l'entreprise)", max_digits=5)),
                ('lead_weight_multiplier', models.DecimalField(decimal_places=2, default=1.5, help_text='Poids relatif du lead en mission équipe (ex. 1.5 = +50%)', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_settings', to='users.enterpriseprofile')),
            ],
            options={
                'db_table': 'enterprise_payroll_settings',
            },
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.UniqueConstraint(fields=('enterprise', 'period_start', 'period_end', 'frequency'), name='uniq_payroll_period_enterprise_range'),
        ),
        migrations.AddConstraint(
            model_name='payrollline',
            constraint=models.UniqueConstraint(fields=('period', 'employee'), name='uniq_payroll_line_period_employee'),
        ),
        migrations.AddConstraint(
            model_name='missionemployeeearning',
            constraint=models.UniqueConstraint(fields=('mission', 'employee'), name='uniq_earning_mission_employee'),
        ),
    ]
