# Generated by Django 4.2.7 on 2026-06-16 12:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant total de la mission', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, help_text='Frais de plateforme (5%)', max_digits=15)),
                ('escrow_amount', models.DecimalField(decimal_places=2, default=0, help_text='Montant bloqué en escrow (100% du budget)', max_digits=15)),
                ('provider_amount', models.DecimalField(decimal_places=2, default=0, help_text='Montant à payer au prestataire', max_digits=15)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('payment_method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('card', 'Carte bancaire'), ('crypto', 'Cryptomonnaie'), ('bank_transfer', 'Virement bancaire')], default='mobile_money', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('operator', models.CharField(blank=True, choices=[('orange', 'Orange Money'), ('wave', 'Wave'), ('mtn', 'MTN Mobile Money'), ('moov', 'Moov Money')], max_length=20)),
                ('external_transaction_id', models.CharField(blank=True, max_length=100)),
                ('external_reference', models.CharField(blank=True, max_length=100)),
                ('escrow_contract_address', models.CharField(blank=True, max_length=42)),
                ('escrow_tx_hash', models.CharField(blank=True, max_length=66)),
                ('blockchain_network', models.CharField(default='sepolia', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='missions.mission')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('card', 'Carte bancaire'), ('bank_account', 'Compte bancaire')], max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('operator', models.CharField(blank=True, max_length=20)),
                ('card_last_four', models.CharField(blank=True, max_length=4)),
                ('card_brand', models.CharField(blank=True, max_length=20)),
                ('card_expiry_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('card_expiry_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_holder_name', models.CharField(blank=True, max_length=100)),
                ('external_token', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_payment_methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason', models.CharField(choices=[('mission_cancelled', 'Mission annulée'), ('no_provider', 'Aucun prestataire'), ('dispute_resolved', 'Litige résolu'), ('other', 'Autre')], max_length=20)),
                ('reason_details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('completed', 'Complété'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment')),
            ],
            options={
                'db_table': 'payment_refunds',
            },
        ),
    ]
