# Generated by Django 4.2.7 on 2026-06-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='country_code',
            field=models.CharField(blank=True, default='+225', max_length=5),
        ),
    ]
