# Generated by Django 4.2.30 on 2026-06-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='country_code',
            field=models.CharField(blank=True, default='+223', max_length=5),
        ),
    ]
