# Generated by Django 4.2.7 on 2026-06-12 07:28

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReputationBonus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bonus_type', models.CharField(choices=[('streak', 'Série de missions'), ('perfect_rating', 'Évaluation parfaite'), ('early_delivery', 'Livraison anticipée'), ('referral', 'Parrainage'), ('special_event', 'Événement spécial')], max_length=30)),
                ('points_added', models.FloatField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reputation_bonuses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReputationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('mission_completed', 'Mission terminée'), ('mission_failed', 'Mission échouée'), ('rating_received', 'Évaluation reçue'), ('dispute_opened', 'Litige ouvert'), ('dispute_resolved', 'Litige résolu'), ('level_up', 'Niveau supérieur'), ('penalty', 'Pénalité'), ('bonus', 'Bonus')], max_length=30)),
                ('old_score', models.FloatField()),
                ('new_score', models.FloatField()),
                ('change_amount', models.FloatField()),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Reputation Histories',
                'db_table': 'reputation_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReputationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('min_score', models.FloatField()),
                ('max_score', models.FloatField()),
                ('min_missions', models.PositiveIntegerField(default=0)),
                ('deposit_discount_percent', models.PositiveSmallIntegerField(default=0)),
                ('priority_access', models.BooleanField(default=False)),
                ('can_accept_urgent', models.BooleanField(default=False)),
                ('color', models.CharField(default='#CD7F32', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('badge_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'reputation_levels',
                'ordering': ['min_score'],
            },
        ),
        migrations.CreateModel(
            name='ReputationPenalty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('penalty_type', models.CharField(choices=[('late_delivery', 'Livraison en retard'), ('no_show', 'Absence'), ('fake_proof', 'Fausse preuve'), ('rude_behavior', 'Comportement inapproprié'), ('cancellation', 'Annulation'), ('spam', 'Spam'), ('fraud', 'Fraude')], max_length=30)),
                ('points_deducted', models.FloatField()),
                ('description', models.TextField()),
                ('is_temporary', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reputation_penalties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReputationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('success_rate_score', models.FloatField(default=40.0)),
                ('rating_score', models.FloatField(default=22.5)),
                ('dispute_score', models.FloatField(default=20.0)),
                ('volume_score', models.FloatField(default=0.0)),
                ('total_missions', models.PositiveIntegerField(default=0)),
                ('successful_missions', models.PositiveIntegerField(default=0)),
                ('failed_missions', models.PositiveIntegerField(default=0)),
                ('cancelled_missions', models.PositiveIntegerField(default=0)),
                ('total_rating_sum', models.PositiveIntegerField(default=0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('average_rating', models.FloatField(default=0)),
                ('dispute_count', models.PositiveIntegerField(default=0)),
                ('dispute_won', models.PositiveIntegerField(default=0)),
                ('dispute_lost', models.PositiveIntegerField(default=0)),
                ('on_time_count', models.PositiveIntegerField(default=0)),
                ('late_count', models.PositiveIntegerField(default=0)),
                ('on_time_rate', models.FloatField(default=100.0)),
                ('level', models.CharField(default='bronze', max_length=20)),
                ('last_calculated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reputation_scores',
                'ordering': ['-overall_score'],
            },
        ),
        migrations.CreateModel(
            name='TrustFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('identity_verified', models.BooleanField(default=False)),
                ('address_verified', models.BooleanField(default=False)),
                ('account_age_days', models.PositiveIntegerField(default=0)),
                ('login_frequency', models.FloatField(default=0)),
                ('response_time_avg', models.FloatField(default=0)),
                ('trust_score', models.FloatField(default=50.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trust_factors',
            },
        ),
    ]
