# Generated by Django 4.2.7 on 2026-06-12 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('missions', '0002_initial'),
        ('reputation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustfactor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_factor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reputationscore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reputation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reputationpenalty',
            name='applied_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties_applied', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reputationpenalty',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='missions.mission'),
        ),
        migrations.AddField(
            model_name='reputationpenalty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reputationhistory',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='missions.mission'),
        ),
        migrations.AddField(
            model_name='reputationhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reputationbonus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to=settings.AUTH_USER_MODEL),
        ),
    ]
